<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
        .container {
            margin-top: 20px;
        }
    </style>
</head>
<body>
<div class="container" role="main">
    <div class="row">
        <div class="col-md-12">
            <a href="/" class="btn btn-primary">Lista</a>
            <h1>Criar Aluno</h1>
            <form method="post">

                <div class="form-group <?php echo isset($erros['name']) ? 'has-error': '' ?>" />
                    <label for="name">Nome</label>
                    <input type="text" maxlength="50" name="name" value="<?= @$oldInput['name']; ?>" class="form-control" placeholder="Nome">
                    <spam class="text-danger"><?php echo @$erros["name"] ?></spam>
                </div>
                <div class="form-group <?php echo isset($erros['cpf']) ? 'has-error': '' ?>">
                    <label for="cpf">CPF</label>
                    <input type="text" name="cpf"  maxlength="11" value="<?= @$oldInput['cpf']; ?>" class="form-control" placeholder="Digite apenas números">
                    <spam class="text-danger"><?php echo @$erros["cpf"] ?></spam>
                </div>
                <div class="form-group <?php echo isset($erros['rg']) ? 'has-error': '' ?>">
                    <label for="rg">RG</label>
                    <input type="text" name="rg" maxlength="14"  value="<?= @$oldInput['rg']; ?>" class="form-control" placeholder="RG">
                    <spam class="text-danger"><?php echo @$erros["rg"] ?></spam>
                </div>
                <div class="form-group <?php echo isset($erros['phone']) ? 'has-error': '' ?>">
                    <label for="phone">Telefone</label>
                    <input type="tel" name="phone" maxlength="13"  value="<?= @$oldInput['phone']; ?>" class="form-control" placeholder="Digite apenas números">
                    <spam class="text-danger"><?php echo @$erros["phone"] ?></spam>
                </div>
                <div class="form-group <?php echo isset($erros['birthday']) ? 'has-error': '' ?>">
                    <label for="birthday">Data de nascimento</label>
                    <input type="text" maxlength="10" name="birthday"  value="<?= @$oldInput['birthday']; ?>" class="form-control" placeholder="Ex.: 06/05/2018">
                    <spam class="text-danger"><?php echo @$erros["birthday"] ?></spam>
                </div>
                <button type="submit" class="btn btn-default">Cadastrar</button>
            </form>
        </div>

    </div>
</div>
</body>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</html>
