<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Slim 3</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <style>
        .container {
            margin-top: 20px;
        }
    </style>
</head>
<body>
<div class="container" role="main">
    <div class="row">
        <div class="col-md-12">
            <a href="/students/create" class="btn btn-primary">Novo</a>
            <h1>Alunos</h1>
            <table class="table">
                <thead>
                <tr>
                    <th>Nome</th>
                    <th>CPF</th>
                    <th>RG</th>
                    <th>Telefone</th>
                    <th>Data de nascimento</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($students as $student){ ?>
                <tr>
                    <td><?php echo $student->name ?></td>
                    <td><?php echo $student->cpf ?></td>
                    <td><?php echo $student->rg ?></td>
                    <td><?php echo $student->phonne ?></td>
                    <td><?php echo $student->birthday ?></td>
                    <td><a href="/students/edit/<?php echo $student->id ?>" class="btn btn-primary">Edit</a></td>
                    <td><a href="/students/delete/<?php echo $student->id ?>" class="btn btn-primary">Delete</a></td>
                </tr>
                <?php } ?>
                </tbody>

            </table>
        </div>

    </div>
</div>
</body>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</html>
